<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twocheckout' => array($vendorDir . '/2checkout/2checkout-php/lib'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Shoplemo\\' => array($vendorDir . '/shoplemo/php-sdk/source'),
);
